server:
  port: 8888

spring:
  cloud:
    config:
      label: video
      server:
        git:
          uri: https://lab.ssafy.com/s03-final/s03p31a409.git
          search-paths: configuration
          password: SmAxtX21UnE173oVFdsD
          username: kimjihyeon
          
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true