#Default port is 8761
server:
  port: 8761


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  serviceUrl:
    defaultZone: https://localhost:8761

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.dcm: DEBUG

security:
  require-ssl: true
server:
  ssl:
    key-store: /etc/letsencrypt/live/example.com/keystore.p12
    key-store-password: Ssafy1234
    keyStoreType: PKCS12
    keyAlias: tomcat
